//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_iconCarrier&quot;&gt; &lt;path d=&quot;M15 20L7 12L15 4&quot; stroke=&quot;#ffffff&quot; stroke-width=&quot;2&quot; stroke- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string arrow_left {
            get {
                return ResourceManager.GetString("arrow-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; transform=&quot;rotate(180)&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_iconCarrier&quot;&gt; &lt;path d=&quot;M15 20L7 12L15 4&quot; stroke=&quot;#ffffff&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string arrow_right {
            get {
                return ResourceManager.GetString("arrow-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_iconCarrier&quot;&gt; &lt;path fill-rule=&quot;evenodd&quot; clip-rule=&quot;evenodd&quot; d=&quot;M5.29289 5.29289C5. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string close_x {
            get {
                return ResourceManager.GetString("close-x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg fill=&quot;#ffffff&quot; version=&quot;1.1&quot; id=&quot;Capa_1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 0 494.239 494.238&quot; xml:space=&quot;preserve&quot; stroke=&quot;#ffffff&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string door_exit_white {
            get {
                return ResourceManager.GetString("door-exit-white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg height=&quot;800px&quot; width=&quot;800px&quot; version=&quot;1.1&quot; id=&quot;Layer_1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; viewBox=&quot;0 0 508 508&quot; xml:space=&quot;preserve&quot; fill=&quot;#000000&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leaf_bad {
            get {
                return ResourceManager.GetString("leaf-bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg height=&quot;800px&quot; width=&quot;800px&quot; version=&quot;1.1&quot; id=&quot;Layer_1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; viewBox=&quot;0 0 508 508&quot; xml:space=&quot;preserve&quot; fill=&quot;#000000&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leaf_good {
            get {
                return ResourceManager.GetString("leaf-good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg height=&quot;800px&quot; width=&quot;800px&quot; version=&quot;1.1&quot; id=&quot;Layer_1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; viewBox=&quot;0 0 508.00 508.00&quot; xml:space=&quot;preserve&quot; fill=&quot;#000000&quot; stroke=&quot;#000000&quot; stroke-width=&quot;0.00508&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; strok [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leaf_too_bad {
            get {
                return ResourceManager.GetString("leaf-too-bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 0 24 24&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; fill=&quot;#7a83ff&quot; stroke=&quot;#7a83ff&quot; stroke-width=&quot;0.00024000000000000003&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_iconCarrier&quot;&gt; &lt;g&gt; &lt;path  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string loguito {
            get {
                return ResourceManager.GetString("loguito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg fill=&quot;#ffffff&quot; version=&quot;1.1&quot; id=&quot;Capa_1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 0 575.953 575.953&quot; xml:space=&quot;preserve&quot; stroke=&quot;#ffffff&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string loguito_conexion {
            get {
                return ResourceManager.GetString("loguito_conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 0 24 24&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; fill=&quot;#000000&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_iconCarrier&quot;&gt; &lt;title&gt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDEFTu`(�GPOSl��G%LN|GSUBC�|`4OS/2rDnx�`STATx�l�`.cmapJ�}V LgaspglyfC��5s�b�head)�Z/�6hhea�        ///X&lt;$hmtxu�F{�lloca�B���8maxp� name�J�l�post�W_�	Kpreph�����������M���`���`�wght�����d�_&lt;�������:*�����1��XK�X^2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Outfit_Regular {
            get {
                return ResourceManager.GetString("Outfit-Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDEFV7{$�GPOS�E�R&amp;N�GSUB�z���dOS/2sn��`STATy�j�`*cmapJ�}V4Lgaspglyf���Xt�dhead*FZ�6hhea        ///�&lt;$hmtx��9[�xloca��Ό�&gt;maxp� name�0�1�post��:l	�preph�����������M�����~�@��wghtX����_&lt;�������:*�~����1X�XK�X^2&quot;frag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Outfit_SemiBold {
            get {
                return ResourceManager.GetString("Outfit-SemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 -1.5 31 31&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:sketch=&quot;http://www.bohemiancoding.com/sketch/ns&quot; fill=&quot;#000000&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap=&quot;round&quot; stroke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string volume_full {
            get {
                return ResourceManager.GetString("volume-full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot;&gt;
        ///        ///&lt;!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools --&gt;
        ///&lt;svg width=&quot;800px&quot; height=&quot;800px&quot; viewBox=&quot;0 -3 30 30&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:sketch=&quot;http://www.bohemiancoding.com/sketch/ns&quot; fill=&quot;#000000&quot; stroke=&quot;#000000&quot;&gt;
        ///        ///&lt;g id=&quot;SVGRepo_bgCarrier&quot; stroke-width=&quot;0&quot;/&gt;
        ///        ///&lt;g id=&quot;SVGRepo_tracerCarrier&quot; stroke-linecap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string volume_muted {
            get {
                return ResourceManager.GetString("volume-muted", resourceCulture);
            }
        }
    }
}
